### ISSUE TITLE
HHHHHHHHHHHHHHHHHHHHHHello!!!!!

### ISSUE THREAD

**Issue by oaeen** [ChangWenhan/Python_Learning_1#1]
Hello bro, can you teach me how to use Python ？hope you dont bu shi tai ju.

**Comment by ChangWenhan** [comment]
fuck it 滚蛋




191181-常文瀚
chang_wh@foxmail.com

中国地质大学（武汉）



------------------ Original ------------------

**Comment by oaeen** [comment]
fuck you guys, why dont you dislike my issues？

**Comment by oaeen** [comment]
ffffffffffffffffffuck
